global:
  scrape_interval:     15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: flower
    static_configs:
      - targets: ['flower:8888']
    basic_auth:
      username: 'admin'
      password: 'evg123312'
  - job_name: headend_app
    static_configs:
        - targets: ['headend_app:9877']